CREATE TABLE USER_PROFILE(UserId INT PRIMARY KEY,
UserName VARCHAR(50) NOT NULL,Password VARCHAR(20), 
EMail VARCHAR(50) NOT NULL, Phone INT NOT NULL,CreatedBy VARCHAR(20) NOT NULL,
CreateDate DATETIME NOT NULL, ModifiedBy VARCHAR(20) NOT NULL, ModifiedDate DATETIME NOT NULL,
RecordStatus BIT NOT NULL, RowGUID VARCHAR(MAX));

INSERT INTO USER_PROFILE VALUES(1001,'Madhan',634512345,'Madhan@GMAIL.COM', 634512345, CURRENT_USER, CURRENT_TIMESTAMP ,CURRENT_USER, CURRENT_TIMESTAMP, 1, NEWID())
INSERT INTO USER_PROFILE VALUES(1002,'Meyyappa',634512345,'Meyyappa@GMAIL.COM', 342353645, CURRENT_USER, CURRENT_TIMESTAMP ,CURRENT_USER, CURRENT_TIMESTAMP, 1, NEWID())
INSERT INTO USER_PROFILE VALUES(1003,'Eshwanth',634512345,'Eshwanth@GMAIL.COM', 675768677, CURRENT_USER, CURRENT_TIMESTAMP ,CURRENT_USER, CURRENT_TIMESTAMP, 1, NEWID())
INSERT INTO USER_PROFILE VALUES(1004,'Agila',634512345,'Agila@GMAIL.COM', 567676576, CURRENT_USER, CURRENT_TIMESTAMP ,CURRENT_USER, CURRENT_TIMESTAMP, 1, NEWID())
INSERT INTO USER_PROFILE VALUES(1005,'Priya',634512345,'Priya@GMAIL.COM', 879645235, CURRENT_USER, CURRENT_TIMESTAMP ,CURRENT_USER, CURRENT_TIMESTAMP, 1, NEWID())
INSERT INTO USER_PROFILE VALUES(1006,'Pooja',634512345,'Pooja@GMAIL.COM', 997653322, CURRENT_USER, CURRENT_TIMESTAMP ,CURRENT_USER, CURRENT_TIMESTAMP, 1, NEWID())
INSERT INTO USER_PROFILE VALUES(1007,'Koushika',634512345,'Koushika@GMAIL.COM', 334665768, CURRENT_USER, CURRENT_TIMESTAMP ,CURRENT_USER, CURRENT_TIMESTAMP, 1, NEWID())

select * from USER_PROFILE

USE PROJECT
---Read User details--
CREATE PROCEDURE SP_read_UserDetails (@User_ID int)
as
select * from USER_PROFILE where USERID=@User_ID

---EXEC --
EXEC SP_read_UserDetails 1004

-- Update user Details--
CREATE PROCEDURE SP_Update_UserDetails (@UserID int,
										@USERNAME VARCHAR(30),
										@PWD VARCHAR(20),
										@EMAIL VARCHAR(50),
										@PHONE INT)
as
update USER_PROFILE set  UserName=@USERNAME,Password=@PWD,
EMail=@EMAIL,Phone=@PHONE,ModifiedBy=CURRENT_USER,ModifiedDate=CURRENT_TIMESTAMP where UserId=@UserID 

---EXEC --
EXEC SP_Update_UserDetails 1004,'AGILa',12754874,'agila@gmail.com',987654321


-- Delete user Details--
CREATE PROCEDURE SP_Delete_UserDetails (@User_ID int)
as
Delete from USER_PROFILE where UserId=@User_ID

--EXEC--
EXEC SP_Delete_UserDetails 1005

SELECT* FROM USER_PROFILE

---TO Read THE LIST OF Order details--
CREATE PROCEDURE SP_list_read_UserDetails 
as
select * from USER_PROFILE 

--EXEC--
EXEC SP_list_read_UserDetails 

----create booking table---
CREATE TABLE BOOK(
CUS_NAME VARCHAR(30) NOT NULL,
CUS_NUMBER NUMERIC(10,0) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
PACKAGE_WEIGHT NUMERIC(6) NOT NULL,
VEHICLE_TYPE VARCHAR(30) NOT NULL,
FROM_ADDRESS VARCHAR(50) NOT NULL,
FROM_CITY VARCHAR(10) NOT NULL,
TO_ADDRESS VARCHAR(50) NOT NULL,
TO_CITY VARCHAR(10) NOT NULL,
DATE_OF_SHIPMENT DATE NOT NULL,
VEHICLE_ID VARCHAR(MAX) NOT NULL,
BOOKING_ID VARCHAR(11) NOT NULL,
INSURANCE BIT NOT NULL,
STATUS_ID BIT NOT NULL,
ModifiedBy VARCHAR(20) NOT NULL,
ModifiedDate DATETIME NOT NULL,
RecordStatus BIT NOT NULL,
RowGUID VARCHAR(MAX));

select* from book;

insert into book values('Agila',231,'aaa@gail.com',100,'truck','chennai','india',
'london','uk',CURRENT_TIMESTAMP,'7865',101,0,0,CURRENT_USER,CURRENT_TIMESTAMP,1,NEWID())
insert into book values('Agila',231,'aaa@gail.com',100,'truck','chennai','india',
'albama','us',CURRENT_TIMESTAMP,'7865',114,0,0,CURRENT_USER,CURRENT_TIMESTAMP,1,NEWID())


---Read Current Order--
CREATE PROCEDURE SP_Booking_Details (@book_ID varchar(11))
as
select * from book where BOOKING_ID=@book_ID

--EXEC--
EXEC SP_Booking_Details 101 

---Reading user Order history--
CREATE PROCEDURE SP_user_order_history (@cus_ID varchar(11))
as
select * from book where CUS_NUMBER=@cus_ID

--EXEC--
EXEC SP_user_order_history 231